name: Deploy static site to docs

on:
  push:
    branches: [ main ]  # or your main branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd portfolio
          npm ci

      - name: Build static site
        run: |
          cd portfolio
          npm run build

      - name: Copy out folder to docs
        run: |
          rm -rf docs
          mkdir docs
          cp -r portfolio/out/. docs/

